name: Update Last Commit Badge

on:
  push:
    branches:
      - main # Ou a branch principal do seu projeto

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código do seu repositório
      - name: Check out a repo
        uses: actions/checkout@v4

      # 2. Pega a mensagem curta (assunto) do último commit
      - name: Get last commit message
        id: last_commit
        run: echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      # 3. Cria a nova badge e atualiza o README
      - name: Update README with last commit message
        run: |
          # Pega a mensagem do commit da etapa anterior
          COMMIT_MSG="${{ steps.last_commit.outputs.message }}"

          # Prepara a mensagem para a URL da badge:
          # 1. Substitui hífens por dois hífens (requisito do shields.io)
          # 2. Substitui espaços por %20 (padrão de URL)
          # 3. Substitui underscores por dois underscores (requisito do shields.io)
          COMMIT_MSG_URL_ENCODED=$(echo "$COMMIT_MSG" | sed 's/-/--/g' | sed 's/_/__/g' | sed 's/ /%20/g')

          # Monta o Markdown completo para a nova badge
          NEW_BADGE="[![Último Commit](https://img.shields.io/badge/commit-${COMMIT_MSG_URL_ENCODED}-blue.svg)](https://github.com/${{ github.repository }}/commits/main)"
          
          # Encontra a linha que contém a badge antiga e a substitui pela nova.
          # Usamos '|' como separador no sed para evitar conflitos com as '/' das URLs.
          # Isso é muito mais seguro que a versão anterior.
          sed -i "s|.*img.shields.io/badge/commit-.*|${NEW_BADGE}|" README.md

      # 4. Faz o commit das mudanças no arquivo README.md
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update last commit badge'
          file_pattern: 'README.md'
